### ISSUE TITLE
Some register and a suggestion

### ISSUE THREAD

**Issue by Vonfry** [jojojames/smart-jump#12]
# Suggestion

 some packages or lang provided some function like `jump-to-module` to a imported file such as `c++ haskell python etc`. Could we add a feature about this?

# register

```
;; elpy is a dev mode for python
(smart-jump-register :modes 'elpy-mode) ; use xref

;; ess-mode is a dev mode for R, ss, etc
(smart-jump-register :modes 'ess-mode) ; use xref

;; lispy is a mode which all lisp-family language can use with.
  (smart-jump-register :modes   'lispy-mode
                       :jump-fn 'lispy-goto-symbol
                       :pop-fn  'pop-tag-mark
                       :refs-fn 'smart-jump-simple-find-references)
```

About the `lispy-mode`, a `should-jump` may be required.

**Comment by jojojames** [comment]
I added something for lispy. I'll be doing some testing/dogfooding for lispy-mode but it may or may not be unstable! Report back if you see any weirdness with lispy-mode.

As for ess-mode and elpy-mode, I don't use those so wouldn't be able to test them very well. I'm open to a PR though.
