### ISSUE TITLE
smart-jump keeps binding itself to M-.

### ISSUE THREAD

**Issue by Fuco1** [jojojames/smart-jump#13]
I don't know why or if this package is responsible but I have something else bound to M-. globally and I'm happy with that.  I suspect that when I define smartjump for a particular mode (php in this case) it automaticlly runs the keybindings also?  Can I disable this somehow?  I have it on `M-'` instead but it still adds itself to `M-.`.

I have to execute `(bind-key "M-." 'sallet-imenu php-mode-map)` in the buffer every time to get my old binding back.

Thanks!

**Comment by jojojames** [comment]
Yup!

Changing these should do.

```
(defcustom smart-jump-bind-keys t
  "If this is true, bind M-.  and M-, upon registering `smart-jump'.

Defaults to t."
  :type 'boolean
  :group 'smart-jump)

(defcustom smart-jump-bind-keys-for-evil t
  "If this is true, bind M-.
and M-, upon registering `smart-jump' for symbol `evil-mode'.

Defaults to t."
  :type 'boolean
  :group 'smart-jump)

```

**Comment by Fuco1** [comment]
@jojojames Hah, I was looking at the definition function that maybe there's a flag there but did not check the globals :blush:  Great work! Thanks for super fast response!
