### ISSUE TITLE
New xref fallback receives a popup with etags backend

### ISSUE THREAD

**Issue by terlar** [jojojames/smart-jump#15]
I noticed I never receive the dumb-jump fallback anymore since the xref fallback was added (https://github.com/jojojames/smart-jump/commit/1b216416a977dc94a6f3b5e40adde7b502d97c2f)

Since my xref is configured with `etags--xref-backend` which I assume is default it always end up popping up the `visit-tags-table` which is quite an annoyance. Have you disabled the etags backend from the xref or have you configured this in some other way?

For now I will try to remove the etags backend since I normally don't use that anyways.

**Comment by jojojames** [comment]
Yeah, I think you're right.

I added it as a result of https://github.com/jojojames/smart-jump/issues/14.

Ideally xref could fall back to dumb-jump. I'm not sure how to fix this yet.

Maybe I can just make it customizable which backend is the 'fallback' so you can skip the xref backend and go straight to dumb-jump.

**Comment by terlar** [comment]
I still think `xref` is a good fall-back as I guess more and more modes are employing that and it seems it actually falls back to dumb-jump after. It is just that it pops up the `visit-tags-table` first and then after you select it, it will try to use that backend and if it doesn't find something, it will use dumb-jump.

It is a bit unfortunate that this interface is so intrusive and asks you for a tag file location every time until you have selected a destination that has one. I think this is a flaw in the `etags--xref-backend`.

I see some approaches:

- Have the `dumb-jump` as an xref backend that is before the etags backend that might be unnecessary work.
- Find a way to configure the `visit-tags-table` to not pop-up if called by another function (non-interactively) or in some other way prevent it from asking.
- Pre-set the tags list so it perhaps won't ask for tags but I guess this partly would render this backend not functioning since that might be part of how it works for those who want to use it.
- Don't use xref as fallback by default and explicitly add it to each mode we know has a good xref implementation.

Perhaps just add a note about it in the README as more users might be running into this. It was quite frustrating before I found a solution. I removed the issue by ensure `xref-backend-functions` don't include the default `etags--xref-backend`. It seems for example for `emacs-lisp-mode` that it sets it to `'(elisp--xref-backend t)` which ensures the etags won't pop up.

**Comment by jojojames** [comment]
Made the change: https://github.com/jojojames/smart-jump/commit/032371014ee6f0bd8c9a7b4f2e3acd393309ece8

Lemme know how it goes. @terlar 

@valignatev I hope this change is satisfactory for you too.

**Comment by valignatev** [comment]
I've notice that tags took over as well, was planning to submit an issue :)
With this change, it's all good for me. Thanks a lot!

**Comment by terlar** [comment]
Yes this solves it, I will let you know if I am missing xref from some other package, I might have registered it manually earlier, like I did with `emacs-lisp-mode`.
