### ISSUE TITLE
`smart-jump-references` can't find ag

### ISSUE THREAD

**Issue by mrcnski** [jojojames/smart-jump#18]
```
Install ag to use ‘smart-jump-simple-find-references-with-ag’.
```

I have The Silver Searcher installed and confirmed that Emacs can find it by running it from `eshell`.

```
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31
```

On OSX.

**Comment by jojojames** [comment]
You'll want the emacs package ag too.

**Comment by mrcnski** [comment]
Thanks. Hmm, is it possible for this to be a dependency of the package?

**Comment by jojojames** [comment]
Hmnn, I prefer optional dependencies where I can have them.

I might want to add a smart-jump-find-references-with-rg at some point and don't want to tack on dependencies users might not want to use.

**Comment by mrcnski** [comment]
Understood. Possible to improve the error message or add a note to the README?

**Comment by jojojames** [comment]
Tweaked the message.
