### ISSUE TITLE
Add autoloads to smart-jump-<mode>-register

### ISSUE THREAD

**Issue by Fuco1** [jojojames/smart-jump#19]
The register functions should be autoloaded so that we don't have to manually require every package before calling register.

**Comment by jojojames** [comment]
Good idea, pushed.

**Comment by Fuco1** [comment]
Sweet!  I'm really enjoying this package.  Was about time to get all the jumping around unified!

**Comment by jojojames** [comment]
Awesome! Glad to hear that.

Definitely let me know if you have any more feedback, good or bad!
