### ISSUE TITLE
How to make smart-jump use helm for xref-find-*

### ISSUE THREAD

**Issue by jclosure** [jojojames/smart-jump#24]
When smart-jump falls back to xref-find-references and xref-find-definitions, how do I make it use helm?  Dumb-jump provides (setq dumb-jump-selector 'helm).  Is there an equivalent construct for smart-jump or configurable mechanism to achieve this?

**Comment by jojojames** [comment]
How does helm work with xref?

**Comment by jclosure** [comment]
Figured it out.
```elisp
(use-package helm-xref
  :demand t
  :ensure t
  :config
  (setq xref-show-xrefs-function 'helm-xref-show-xrefs))
```
Now M-. via smart-jump uses helm-xref.
