### ISSUE TITLE
`xref-find-definitions' does not jump directly but asks for input

### ISSUE THREAD

**Issue by terlar** [jojojames/smart-jump#3]
With a setup like:
```
(smart-jump-register :modes 'emacs-lisp-mode)
```

If I press <kbd>M-.</kbd> when I am standing on a `function`/`require` symbol I am presented with a list with the symbol pre-populated as default option and have to accept that with an extra step.

However if I bind `xref-find-definitions` directly to the keybinding. It doesn't present the list, but instead jumps directly to the reference.

I am not sure why this happens, since it should use the same function in the backend, but must have something to do with how it is called. I have also tried to set the `jump-fn` explicitly to `xref-find-definitions` and this doesn't change the behavior.

**Comment by jojojames** [comment]
Thanks, I was wondering the same thing. I thought that was how it always behaved and didn't look further.

Can you test the latest commit to see if it helps?

**Comment by terlar** [comment]
Yes this works now, thank you for the quick feedback!

I am currently migrating my configuration to use smart-jump and it works very well so far. Thank you.

**Comment by jojojames** [comment]
Thanks! Glad you like it so far.
