### ISSUE TITLE
New invalid dependencies

### ISSUE THREAD

**Issue by tarsius** [jojojames/smart-jump#8]
`smart-jump` recently started depending on `clojure` and `erlang-mode`, but as far as I can tell no packages provide these features. However packages named `clojure-mode` and `erlang` exist, and those provide the features by the same names.

**Comment by terlar** [comment]
The `erlang-mode` one was my bad, I checked my package require config wrong, should be fixed with this one: https://github.com/jojojames/smart-jump/pull/9

**Comment by jojojames** [comment]
Woops. Thanks, fixed.

**Comment by tarsius** [comment]
Thanks!
